### ISSUE TITLE
About your username

### ISSUE THREAD

**Issue by alsterholm** [talada/auto-taxonomy#2]
Hi @talada!

I'm very interested in your username here at GitHub, as I have a project named that way. Could you please send me an email at andreas@rocketship.se so that we can discuss it?

Best regards,
Andreas.

**Comment by nottalada** [comment]
Cool, so first: Yes, I'll give you the account on the condition that after
your development, if I ever want it back, I get it back.

Looks like you're making a game called Talada? (My last name is Talada)
Need any help?

I know PHP and Python pretty well. I'm also a pretty decent artist and can
draw Fantasy/Sci-Fi art.

I'll attach some sample code and a sketch. I can draw in a realistic or
anime style. I prefer to use Autodesk Sketchbook Pro/GIMP/Inkscape/Manga
Studio. But I can use photoshop/illustrator.

I would show you sample python code but I practically only develop in
Python for work.

I have a degree in Web Design but I'm pretty slick in Inkscape at making
web mockups and graphics.

Let me know if you could use the help.
